# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_editor_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={},
        ),
        migrations.AddField(
            model_name='article',
            name='article_Image',
            field=models.ImageField(blank=True, upload_to='article/'),
        ),
    ]
