# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20181101_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_Image',
        ),
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='articles/'),
        ),
    ]
